// examples/solid/src/components/Clock/index.tsx
import { type Component, createSignal, createEffect } from 'solid-js';

const Clock: Component = () => {
  const [now, setNow] = createSignal(new Date());

  createEffect(() => {
    const timer = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(timer);
  });

  return (
    <div>
      <p>It is {now().toLocaleTimeString()}.</p>
    </div>
  );
};

export default Clock;

// examples/react/src/comps/clock/index.tsx
import React, { useEffect, useState } from 'react';

export default function Clock() {
  const [now, setNow] = useState(new Date());
  
  useEffect(() => {
    const timer = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(timer);
  });

  return (
    <div>
      <h1>React Clock 1</h1>
      <p>It is {now.toLocaleTimeString()}.</p>
    </div>
  );
}
