// examples/react/src/components/welcome/index.tsx
import React from 'react';
import { FarmCard } from '../card/index';
import { ButtonAction } from '../button/index';
import feature from '../../../assets/feature.svg';
import logo from '../../../assets/logo.png';
import light from '../../../assets/light.svg';
import plugin from '../../../assets/plugin.svg';
import './index.css';

export function Welcome() {
  return (
    <div className="farm-container">
      <img className="logo" src={logo} alt="" />
      <FarmCard>
        <div className="main-desc">
          <h2 className="main-sub-title">
            Get started With
            <span className="main-content"> React + Farm</span>
          </h2>
          <span className="main-content">
            Super fast web building tool written in Rust.
          </span>
        </div>
      </FarmCard>
      <div className="farm-desc">
        <div className="farm-desc-left">
          <FarmCard>
            <div className="container-box">
              <img src={feature} alt="" />
              <div className="rich-desc">
                <span className="sub-title">Rich Features</span>
                <span className="rich-content">
                  Farm support compiling Html, Css, Js/Jsx/Ts/Tsx, Static Assets
                  natively, support lazy compiling, partial bundling and more.
                </span>
              </div>
            </div>
          </FarmCard>
          <div className="farm-desc-right">
            <FarmCard>
              <div className="container-box">
                <img src={plugin} alt="" />
                <div className="fully-desc">
                  <span className="sub-title">Fully Pluggable</span>
                  <span className="fully-content">
                    Everything inside Farm is powered by plugins, you can
                    achieve anything you want by writing a plugin. Support both
                    Rust and Js plugins.
                  </span>
                </div>
              </div>
            </FarmCard>
          </div>
        </div>
        <FarmCard>
          <div className="action-box">
            <div className="container-box">
              <img src={light} alt="" />
              <div className="fast-desc">
                <span className="sub-title">Super Fast </span>
                <span className="fast-content">
                  Farm's compiler is written in Rust, with multi-threading,
                  lazy/asynchronous compilation and persist caching, Farm can
                  start a project in milliseconds, perform a HMR update within
                  10ms.
                </span>
              </div>
            </div>
            <div className="action">
              <ButtonAction to="https://farm-fe.github.io/docs/quick-start">
                Quick Start
              </ButtonAction>
              <ButtonAction to="https://farm-fe.github.io/docs/why-farm">
                Why Farm ?
              </ButtonAction>
            </div>
          </div>
        </FarmCard>
      </div>
    </div>
  );
}

// packages/cli/templates/vue/src/components/Welcome.vue
<template>
  <div class="farm-container">
    <img class="logo" src="../../assets/logo.png" alt="" />
    <h1>Welcome to <span class="title">Farm!</span></h1>
    <FarmCard>
      <div class="main-desc">
        <h2 class="main-sub-title">
          Get started With
          <span class="main-content">Vue + Farm</span>
        </h2>
        <span class="main-content">
          Super fast web building tool written in Rust.
        </span>
      </div>
    </FarmCard>
    <div class="farm-desc">
      <div class="farm-desc-left">
        <FarmCard>
          <div class="container-box">
            <img src="../../assets/feature.svg" alt="" />
            <div class="rich-desc">
              <span class="sub-title">Rich Features</span>
              <span class="rich-content">
                Farm support compiling Html, Css, Js/Jsx/Ts/Tsx, Static Assets
                natively, support lazy compiling, partial bundling and
                more.</span
              >
            </div>
          </div>
        </FarmCard>
        <div class="farm-desc-right">
          <FarmCard>
            <div class="container-box">
              <img src="../../assets/plugin.svg" alt="" />
              <div class="fully-desc">
                <span class="sub-title">Fully Pluggable</span>
                <span class="fully-content">
                  Everything inside Farm is powered by plugins, you can achieve
                  anything you want by writing a plugin. Support both Rust and
                  Js plugins.</span
                >
              </div>
            </div>
          </FarmCard>
        </div>
      </div>
      <FarmCard>
        <div class="action-box">
          <div class="container-box">
            <img src="../../assets/light.svg" alt="" />
            <div class="fast-desc">
              <span class="sub-title">Super Fast </span>
              <span class="fast-content">
                Farm's compiler is written in Rust, with multi-threading,
                lazy/asynchronous compilation and persist caching, Farm can
                start a project in milliseconds, perform a HMR update within
                10ms.</span
              >
            </div>
          </div>
          <div class="action">
            <ButtonAction to="https://farm-fe.github.io/docs/quick-start"
              >Quick Start</ButtonAction
            >
            <ButtonAction to="https://farm-fe.github.io/docs/why-farm"
              >Why Farm ?</ButtonAction
            >
          </div>
        </div>
      </FarmCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import FarmCard from './Card.vue';
import ButtonAction from './Button.vue';
</script>

<style scoped>
.main-content {
  font-weight: bold;
  font-size: 28px;
  background: var(--accent-gradient);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  color: transparent;
  background-size: 400%;
  background-position: 0%;
}
.action-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 62px;
}
.action {
  display: flex;
  gap: 40px;
}
.farm-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  height: 100%;
  align-items: center;
  padding: 2rem 1rem;
  gap: 1.7rem;
}
.farm-desc {
  display: flex;
  justify-content: space-between;
  gap: 32px;
}

.container-box {
  display: flex;
  align-items: center;
  gap: 24px;
}
.container-box img {
  width: 70px;
  height: 70px;
}
.farm-desc-left {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.main-desc {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
}

.rich-desc,
.fast-desc,
.fully-desc {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.rich-content,
.fast-content,
.fully-content {
  color: #666;
}

h2 {
  margin: 15px;
}
.sub-title {
  font-size: 1.25rem;
  font-weight: 600;
}

.logo {
  width: 450px;
}
.title {
  background: var(--accent-gradient);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  color: transparent;
  background-size: 400%;
  background-position: 0%;
}

h1 {
  margin: 0;
}
.img {
  width: 100px;
  height: 100px;
}
</style>
