// examples/react/src/comps/counter-button/index.tsx
import React, { useEffect, useState } from 'react';

import './index.css'

const COUNT_DOWN = 60;
const BUTTON_TEXT = 'Send';
console.log(BUTTON_TEXT)
export function CounterButton() {
  const [count, setCount] = useState(COUNT_DOWN);
  const [text, setText] = useState(BUTTON_TEXT);
  const [timer, setTimer] = useState(null as null | number);
  const [pause, setPause] = useState(false);

  useEffect(() => {
    return () => {
      if (timer) {
        clearInterval(timer);
      }
    }
  }, [timer]);

  const countdown = () => {
    console.log(timer, pause, count, text);
    setCount(count => {
      if (count == 0) {
        clearInterval(timer as number);
        setText(BUTTON_TEXT);
        return 0;
      }

      setText(`${count - 1}`);
      return count - 1;
    });
  };

  return <button className='counter-button' onClick={() => {
    if (timer && pause === false) {
      setPause(true);
      setText('Pause')

      clearInterval(timer);
      return;
    } else if (pause === true) {
      setPause(false);
      setText(`${count}`);

      setTimer(setInterval(countdown, 1000));
      return;
    }

    console.log(timer, pause, count, text);
    const t = setInterval(countdown, 1000);

    setText(`${COUNT_DOWN}`);
    setTimer(t);
  }}>{text}</button>
}

// examples/vue/src/comps/counter-button/index.vue



<template>
  <button className='counter-button' @click="handleClick"> {{ text }} </button>
</template>

<script lang='ts'>
import { defineComponent, ref } from 'vue';

import './index.css'

const COUNT_DOWN = 60;
const BUTTON_TEXT = 'Send';


export default defineComponent({
  setup() {
    const count = ref(COUNT_DOWN)
    const text = ref(BUTTON_TEXT)
    const timer = ref(-1)
    const pause = ref(true)
    const countdown = () => {
      if (count.value === 0) {
        clearInterval(timer.value)
        text.value = BUTTON_TEXT
        count.value = COUNT_DOWN
        pause.value = true
      }
      else {
        count.value = count.value - 1
        text.value = count.value + "";

      }
    };

    const handleClick = function () {
      if (timer.value && pause.value === false) {
        pause.value = true
        text.value = 'Pause'
        clearInterval(timer.value);
      } else if (pause.value === true) {
        pause.value = false
        text.value = `${count.value}`
        timer.value = setInterval(countdown, 1000)
      }
      else {
        const t = setInterval(countdown, 1000);
        text.value = COUNT_DOWN + ""
        timer.value = t
      }
    }

    return {
      handleClick,
      count,
      text,
      timer,
      pause,
      countdown
    }
  }

})

</script>
