// examples/solid/src/components/Title/index.tsx
import { type Component } from 'solid-js';

import logo from '../../../assets/logo.svg';
import './index.css';

export const Title: Component = () => {
  return (
    <div class="farm-title-wrapper">
      <img src={logo} class="farm-logo" alt="Farm Logo" />
      <h1 class="farm-title">Farm</h1>
    </div>
  );
};

// examples/react/src/comps/title/index.tsx
import React from 'react';
import { Button } from 'antd';
import './index.css';

import logo from '../../../assets/logo.svg';

export function Title() {
  return (
    <div className="farm-title-wrapper">
      <Button>test</Button>
      <img src={logo} className="farm-logo" alt="Farm Logo" />
      <h1 className="farm-title">Farm</h1>
    </div>
  );
}
